### PR TITLE
14 new population importer

### LINKED ISSUE #14: New Population Importer (e.g. RIL, NAM)
The functionality described in #13 requires the germplasm already to exist.

## Original Needs Description

We have a number of RIL populations that need to be entered into KnowPulse. We currently save these as shown below. This importer should be able to select the existing RIL population stock and then using a list of RIL individuals provided via a file, the importer should create entries in the stock table for each RIL individual and add the needed relationships to connect it to the population.
Work Notes-61

## Additional considerations

 - We may want to code this as a generic individual of population importer for more use cases. This could be done by allowing any stock record to be selected as the "population" and the ability to select the relationship type to use.
 - Since we are creating the population (i.e. RIL) individuals, we will need to know their organism, type, name and uniquename. 
 - We typically create our uniquename using a pattern so we will want to support that similar to the other importers Yichao made. 
 - For max flexibility we may want to have the organism and type in the file as well so it doesn't have to be the same throughout the population.
 - We may also want to allow the uniquename to be included in the file or calculated via pattern if not provided.

### Form

- Population Stock*: autocomplete pulling from all stock records
- Relationship Type*: autocomplete pulling from all cvterms, is_individual_of_population is the default
- Population Stock Position in Relationship*: Radios with subject + object, description includes an example, default is object
- Uniquename Pattern: See Yichao's importers and use same mechanism. I think it's a prefix approach.
- File Upload: provided by Tripal importer

### File

- Name: the name of the RIL individual
- Type: the name of the cvterm which should be used for the stock record, must exist
- Scientific Name: the genus + species of the organism to be used for the stock record, must exist
- Uniquename (optional): the uniquename to use if you do not want to use the pattern.

### PR DESCRIPTION
**Pull request by reynoldtan**
## Metadata

 - Issue #14 New Population Importer (e.g. RIL, NAM) 

- [x] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Testing?

- [ ] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [x] This PR includes automated testing

TO TEST:
1. Pull changes to this repository and point to the branch 14-new-population-importer
2. Set permission to importer by accessing admin/people/permissions and locate Tripal in the list of modules on the left hand side panel. Scroll to the bottom to find Importer: Use the Germplasm Population Importer and check checkbox corresponding to Administrator user then click Save Permission Button.
3. Clear Cache (2x)
4. Under Tripal/Data Loaders - Access Germplasm Population Importer.
5. Since in a KP clone this modules had been installed prior, Click on Configure module to set Relationship Verb CV and default Prefix value.  I use **stock_relationship** for verb cv and **GERM** for prefix value.
6. Go back to the Importer page.
7. Create a tsv file as described by the Importer File requirements. An example file below can be used directly or as a model.

[import me.zip](https://github.com/UofS-Pulse-Binfo/uofspb_germplasm/files/10806454/import.me.zip)

You may test validation by altering values in this data file such as:
A. Re-uploading the same file will trigger germplasm already exists
B. Use a non-existing type or organism will trigger invalid type or organism, respectively
C. A completely empty file
D. Unexpected or missing column header

The file should create 3 stocks with one using a custom unquename while the other 2 will rely on the default prefix.

8. This importer is equipped with a population viewer to verify the imported stocks.
admin/tripal/extension/germplasm_population_importer/configure
and expand View Population.

### CODE REVIEW

**Comment by carolyncaron** [comment]
Thanks for the PR and great demo of this functionality, Reynold! Most of my suggestions are minor, let me know if anything needs clarification.

### Configuration page:
- When choosing a cv term on the configuration page, it would be really helpful if the list of cv terms was sorted in an intuitive way, such as alphabetically. Right now the list feels very random and it was difficult to find the term I was looking for.
- The term "Load Population Individuals" makes me think it is synonymous with importing data, which isn't the case here. Perhaps a better word would be "List" or "Check for"?
- I think it would be helpful to include your figure from the upload page about object/subject placement under the "Stock Position" dropdown to help remind the admin when selecting. It's not a big deal though since there's only 2 options to choose from 😅 
### Upload page:
- I think that the error message that reports when a germplasm cannot be entered should also let the user know what germplasm name triggered the error, is possible. The line # is useful but it threw me off to see there was an issue on line 2 and it refers to the first germplasm since the header is technically line 1. 
- I tested a germplasm name of only symbols: "@#$%^" and it was imported. However, I was curious and also was able to create a germplasm accession with a similar name of only symbols without the importer. 😜 So this does not pertain to this PR so long as any existing rules for valid germplasm names are being respected, but I thought I'd bring it up in case we want to impose some limitations (maybe in Tripal 4)? Or we could just continue to be very trusting of administrators. 😉 
- I was able to successfully import a file with duplicate lines without Uniquenames. 😬 Screen Shot 2023-03-02 at 6 56 50 PM
I worry that it wouldn't be that uncommon for a duplicate line to end up in a large upload file by accident, and the admin may not catch that it has also now been duplicated at the database level by this importer. If there is a good reason (though I can't think of one personally) to include duplicate germplasm names, perhaps the importer could allow it when different Uniquenames are provided for them in the file, since that feels more intentional and less accident-prone. These are just my thoughts, but I think a warning at minimum should be provided even when Uniquename is different!

**Review by carolyncaron — COMMENTED** [review]
Thanks for the PR and great demo of this functionality, Reynold! Most of my suggestions are minor, let me know if anything needs clarification.

### Configuration page:
- When choosing a cv term on the configuration page, it would be really helpful if the list of cv terms was sorted in an intuitive way, such as alphabetically. Right now the list feels very random and it was difficult to find the term I was looking for.
- The term "Load Population Individuals" makes me think it is synonymous with importing data, which isn't the case here. Perhaps a better word would be "List" or "Check for"?
- I think it would be helpful to include your figure from the upload page about object/subject placement under the "Stock Position" dropdown to help remind the admin when selecting. It's not a big deal though since there's only 2 options to choose from 😅 
### Upload page:
- I think that the error message that reports when a germplasm cannot be entered should also let the user know what germplasm name triggered the error, is possible. The line # is useful but it threw me off to see there was an issue on line 2 and it refers to the first germplasm since the header is technically line 1. 
- I tested a germplasm name of only symbols: "@#$%^" and it was imported. However, I was curious and also was able to create a germplasm accession with a similar name of only symbols without the importer. 😜 So this does not pertain to this PR so long as any existing rules for valid germplasm names are being respected, but I thought I'd bring it up in case we want to impose some limitations (maybe in Tripal 4)? Or we could just continue to be very trusting of administrators. 😉 
- I was able to successfully import a file with duplicate lines without Uniquenames. 😬 Screen Shot 2023-03-02 at 6 56 50 PM
I worry that it wouldn't be that uncommon for a duplicate line to end up in a large upload file by accident, and the admin may not catch that it has also now been duplicated at the database level by this importer. If there is a good reason (though I can't think of one personally) to include duplicate germplasm names, perhaps the importer could allow it when different Uniquenames are provided for them in the file, since that feels more intentional and less accident-prone. These are just my thoughts, but I think a warning at minimum should be provided even when Uniquename is different!

**Comment by reynoldtan** [comment]
Great review and good catch Carolyn. I've made changes to the importer as outlined in your review:

1. Alphabetized all select fields
2. Stock position in config page now with illustration identical to the importer
3. Replaced label of submit button to List Population Individuals.
4. Error messages contain both the Germplasm Name and the Line Number.
5. Did not implement validation of Name made up of special chars - tricky to implement - I will just rely on the elevated permission of the user who will use this importer not to use this kind of character combination 😁 
6. It will check duplicate lines in file for both Name+Type+Scientific Name+Uniquename and just the Uniquename. Just like your comment, I have allowed identical lines with the exception of Uniquename to proceed and a warning be issued. Further, the warning is added in advance to the expected headers description section as a Note.

**Comment by ruobinLiu** [comment]
Hi Reynold, thank you for the PR and thank you for being so patient and helpful with my questions!

**On the Configuration page**, I agree with Carolyn's point 1, so thank you for alphabetized all select fields.
**On the Upload page**, I tested the following 4 scenarios as suggested, and found the Error/Warning are all very intuitive, which will be very helpful in real cases.

✅ A. Re-uploading the same file will trigger germplasm already exists
✅ B. Use a non-existing type or organism will trigger invalid type or organism, respectively
✅ C. A completely empty file
✅ D. Unexpected or missing column header

I used the RIL individual as examples that are awaiting to be uploaded for further rigorous tests. As shown in the screenshot, custom uniquenames and default prefix uniquenames all work as expected 👍 
Screenshot 2023-03-06 at 2 48 51 PM

I encountered two issues during my test, which we already covered in Teams chat but I want to bring them up again:
1. To upload any individual that has Type = F2, there are two potential terms to use,  **KPstock_props** or **Tripal**. I am unsure the difference between the two terms and how to use them... 
MicrosoftTeams-image (3)

2. The ERROR could be a bit ambiguous sometimes: I received the below error when I messed up with the file format (have the info mismatch with the column headers), but the error made me think that I used the wrong term under the Type column, so I keep fixing and trying without knowing the real mistake. Therefore, I wonder if it is possible to set the error message point to the issue? Or alternatively, we could emphasis that the file should be prepared using the correct format.
MicrosoftTeams-image (4)

**Comment by reynoldtan** [comment]
Awesome review Ruobin! I have modified some text in the tsv file description and added a link to a template file that user could download pre-filled with required column header and a sample line. I hope this will prevent user from formatting the file incorrectly. It is tricky to catch and requires more logic to check whether file has space or tab delimiter and display appropriate error, I hope this additional instructions about the file would suffice to prevent the same issue.

Screen Shot 2023-03-07 at 10 04 47 AM

**Comment by ruobinLiu** [comment]
Thank you Reynold! I love the idea of having a template file, it will be extremely helpful! 
Look all good to me now!

**Review by ruobinLiu — APPROVED** [review]

**Comment by carolyncaron** [comment]
Thanks for these changes Reynold, and I also love the changes from Ruobin's suggestions! I re-tested my files and it is all passing with flying colours 🌈 😁  The final suggestion I would make is to add the actual name of the germplasm to the warning message in the case when there is a duplicate name with different uniquename. You may want to think about how to format the message if there were 2 or more duplicates in the file. Perhaps something like:
> The following germplasm Names were detected in the file as duplicates with dissimilar Uniquenames:
> Name1
> Name2

**Comment by reynoldtan** [comment]
Duplicate lines, by Name added to the warning message 
image

**Review by laceysanderson — APPROVED** [review]
These are all picky comments and it can be merged.

That said:
- Please do not give the user an error on empty line. They should just be skipped, both within the file and at the end.
- I would never do this much validation in the formValidate since that happens in the page load. That said, I did get Carolyn to test a 2000 line file and it was pretty fast so it's likely ok... it just always makes me very cautious to process an entire file in the page load.
- I would extend the file types allowed to include `.txt` file endings. When you export from excel as tab delimited it gives a `.txt` file ending and currently that has to be manually changed.

**Pull request merged**
