### PR TITLE
Collection more options

### PR DESCRIPTION
**Pull request by reynoldtan**
## Metadata

 - Issue #16 
 Items number 2 and number 3, download link and search functionality, respectively.

- [x] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description

This PR adds germplasm search in a collection and provides a download link to export germplasm collection list into a csv file.

image

## Testing?

- [ ] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

TO TEST:
1. Pull changes to this branch in your KP clone.
2. Switch to branch collection-more-options
3. Clear Cache
4. Navigate to Content / Tripal Content Types and filter the list to show only germplasm collection content type.
5. View a collection.

### CODE REVIEW

**Comment by ruobinLiu** [comment]
Yes! I am able to find the download link, followed by download the AGILE LDP germplasm collection in the .cvs file. Everything in the file looks correct too! Nice job Reynold!

**Review by laceysanderson — APPROVED** [review]
Code review looks good ✅

**Review by carolyncaron — CHANGES_REQUESTED** [review]
Hi Reynold, there were a couple of things that I noticed:

1. In the autocomplete dropdown for the search, each of the lines for the LDP had the number "4" appended at the end. For my own test collection, the number "5" was appended. 
2. In my test collection, one of the germplasm (CDC Maxim SB-19) is unpublished. So when I download it, that one is excluded in my spreadsheet. I can understand why this would happen, but I think that someone who wants to download a table would expect every row in the table on the website to also be present in the download. 
Screen Shot 2023-02-02 at 3 56 10 PM
Screen Shot 2023-02-02 at 4 01 30 PM

Note: You'll notice in my second screenshot there is a small box under the listing with "Loading content". It also appeared on the AGILE collection page but I didn't want to include the whole page in my screenshot. I don't think this has to with this PR since I switched back to my master branch, cleared the cache, and it was still there. I don't see it on portal, however. Might be something worth looking into (I'll try booting up a new clone and try it again next week!) but it alone is not a reason to prevent merging this PR :)

**Comment by reynoldtan** [comment]
Thanks for the review. The recent commit is meant to fix the issues regarding dissimilar list and numeric value seen in search field.

To clarify decisions made how list is created:

1. Use the function germcollection_get_germplasm(stock_collection_id) in Widget (create collection), Formatter (view), Field instance and Export functionality that will serve consistent listing of germplasm showing only published stocks (unpublished stocks are excluded).
2. The Widget (create collection) is equipped with a validation to prevent collection authors from adding germplasm of unpublished type.
Screen Shot 2023-02-28 at 3 06 24 PM


3. Please note that for a collection that has unpublished stock added prior to this fix will be excluded but will be part of the list shown by the Filter collection (outbound link) provided by the Formatter (view).

**Review by carolyncaron — APPROVED** [review]

**Pull request merged**
