### PR TITLE
Germplasm collections

### PR DESCRIPTION
**Pull request by laceysanderson**
## Metadata

 - Issue #n/a

- [ ] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

## Description

We need a page for the LDP and connections between experiments and the germplasm the being assayed. Eventually RILs will also become stock collections.

## Upgrade from separate modules
https://kp-germplasm.readthedocs.io/en/latest/install/install.html#upgrade-path-from-separate-modules

### Adding a stock collection for testing
Currently there is no way to add germplasm to a stock collection through the UI... The following instructions will allow you to add it at the database level. Note: these instructions assume you have an empty database, if you don't make sure to update the IDs in the query for organism, project and stock collection as needed. Also make sure the type_id is equal to that for germplasm accession content types.

1. Insert Data.
```sql
SELECT * FROM chado.cvterm WHERE name='accession';
 cvterm_id | cv_id |   name    | definition | dbxref_id | is_obsolete | is_relationshiptype 
-----------+-------+-----------+------------+-----------+-------------+---------------------
      2820 |    12 | accession |            |      3126 |           0 |                   0
(1 row)

INSERT INTO chado.stock (organism_id, type_id, uniquename, name) SELECT 1, 2820, 'SGL000'||i, 'Sunny lo'||i FROM generate_series(100,175) as t(i);
INSERT INTO chado.stockcollection (type_id, uniquename, name) VALUES (2820, 'SGL panel', 'Sunny Ground Loomers');
INSERT INTO chado.stockcollection_stock (stockcollection_id, stock_id) SELECT 1, stock_id FROM chado.stock WHERE uniquename~'SGL000';
INSERT INTO chado.project (name, description) VALUES ('SGL height study', 'Studying the heigh of the Sunny ground loomers!');
INSERT INTO chado.project_stockcollection (stockcollection_id, project_id) values (1,1);
```
2. Create a stock collection content type: https://kp-germplasm.readthedocs.io/en/latest/germcollection/germcollection.html
3. Publish pages for your stock collection, germplasm accessions and projects.
4. Go to each content type manage fields page (Admin > Structure > Tripal Content Types > germplasm accession > manage fields) and click "check for new fields" to ensure the fields have attached.

## Testing?

- [x] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

**Make sure you are on the `germcollection` branch. **

### co_010__germplasm field
This field creates an ajax paged list of the member germplasm on a germplasm collection page.
1. Make sure this field is attached to the germplasm collection content type you created above.
2. Go to the `28, 79, SGL panel, , , accession` germplasm collection page and test the field:
    - there should be 10 items per page and 8 pages
    - the broken ajax spinner is a Tripal bug
    - each page should have a unique set of 10 items in order.
    - paging should work ;-p

### local__project_germcollection
This field shows a link to germplasm collections on a project page.
1. Make sure this field is attached to the germplasm collection content type you created above.
2. Go to the `SGL height study` project page and check that there is a working link to the germplasm collection.
3. Test that the germplasm collection can be removed and re-added using the edit form for the project.
    - There should be an autocomplete for the germplasm collection name.

### CODE REVIEW

**Comment by reynoldtan** [comment]
Reviewed RIL summary section and it worked!

Screen Shot 2020-05-08 at 9 19 57 AM (2)

I had difficulty getting relevant fields to automatically add during install after several attempts. The error throughout my test had always been 

```[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for ‘cv_id’ on table ‘cvterm’ returned no results where the definition supplied was Array(  [name] => tripal)```

and 

```PHP Fatal error: Cannot declare class rdfs__type, because the name is already in use in my/sites/all/modules/tripal/tripal/includes/TripalFields/rdfs__type/rdfs__type.inc on line 76```


I got past the latter error by enabling the module in this order:
1. KP Germplasm
2. RIL Summary 
THEN, run jobs generated (important).

And resolved the former error by manually inserting a cv entry name=tripal, then

3. Enable germcollection

Suggestion for the documentation:
1. In the event of successful module installation and expected field not being automatically created, provide a manual creation of the field.
2. How to add stock of type ```F2``` that will become count in the summary matrix.




The KP in the module name may indicate this is a module for KnowPulse. Installing using the Drupal Module interface sorts this module into Tripal Germplasm and not where it is expected in Knowpulse Extension section.
Screen Shot 2020-05-07 at 8 52 53 AM

**Comment by laceysanderson** [comment]
Hi @reynoldtan,

I'm still not able to replicate either of the errors you encountered:

> [site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_select_record: the foreign key definition for ‘cv_id’ on table ‘cvterm’ returned no results where the definition supplied was Array( [name] => tripal)

The Tripal CV is added when you prepare Drupal and Tripal. I've tested on 2 new Tripal dev sites and it's added every time during this step.

> PHP Fatal error: Cannot declare class rdfs__type, because the name is already in use in my/sites/all/modules/tripal/tripal/includes/TripalFields/rdfs__type/rdfs__type.inc on line 76

I have Tripal checked and there is no rdfs__type class anywhere in this package so this error must be caused by your environment.

> In the event of successful module installation and expected field not being automatically created, provide a manual creation of the field.

There was a bug in the RIL field being added properly. I have fixed that and thus the documentation is not needed.

> How to add stock of type F2 that will become count in the summary matrix.

I've confirmed the RIL summary module works with the default RIL content type added by Tripal. Furthermor, you can add to the matrix following these instructions: https://kp-germplasm.readthedocs.io/en/latest/rilsummary/rilsummary.html#adding-rils-to-the-summary. I also added help text to the bottom of the matrix to lead admin to this documentation.

**Comment by Jiu9Shen** [comment]
tried twice, still can not make it work, the problem is related to find `tripal content type: Germplasm Collection`, also, it is not available in list of Add Tripal Content Types.

**Comment by laceysanderson** [comment]
I just renamed the module as per @reynoldtan's comment regarding the `kp_` prefix. to upgrade:

Execute the following from within the kp_germplasm module directory.
```
drush dis kp_germplasm rilsummary germcollection -y
git pull
drush en uofspb_germplasm rilsummary germcollection -y

**Comment by laceysanderson** [comment]
@Jiu9Shen I just tried this repeatedly on a Tripal Dev site and creating the content type works for me. Additionally, I tried it on a brand new KnowPulse clone and as long as you delete the old "Germplasm Collection" content type first, it works there as well. I've deleted the old content type from portal to ensure we don't forget this critical step (especially since it was not being used).

**Comment by Jiu9Shen** [comment]
it works good on general tripal site, but I still can not find the tripal content type (Germplasm Collection) on my local KP test site. Since @laceysanderson tested on kp dev site and it worked find, I would guess it's something funny with my local kp test site.

**Comment by laceysanderson** [comment]
Great, Thanks for the review!

**Pull request merged**
