### PR TITLE
Updated Germplasm Collection create and view functionality

### PR DESCRIPTION
**Pull request by reynoldtan**
This PR creates functionality to create and view germplasm collection.

## Metadata

This fixes the issue https://github.com/UofS-Pulse-Binfo/uofspb_germplasm/issues/13

- [x] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Description

Created a custom Tripal Field where the formatter is configured to view collection and widget is setup to create/insert germplasm to a collection.

## Testing?

- [ ] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

1. Clone uofspb_germplasm and switch to branch add-stock-to-collection.
2. Start a KP clone and point the volume to the module in Step 1 (see KP Clone repository). 
3. Navigate to Structure/Tripal Content Types and select managed fields for Germplasm Collection.

4. If it was installed previously, remove the field Germplasm List co_0010__germplasm by clicking delete link under the OPERATIONS column in Germplasm Collection field manager page.

image

5. Re-install the Germplasm Collection Field. This ensures that field variables are properly initiated and additional functionality is recognized by Drupal.

image

Type: Germplasm List or Germplasm Collection in the Add new field and select Germplasm List in the field type selectbox. Widget for this field will default to Germplasm List.

Click image (Which is located at the bottom of the page)

After clicking Save button, you will be redirected to Germplasm Collection Field Settings page. Accept all default values for this field and scroll down to bottom of the page and click image

6. Once saved, navigate back to field manager page and click on Manage Display tab and inspect the newly created field if it ended up under Disabled fields. 
image

If this is the case, click and drag crosshair icon inline with the field name and move it out of the disabled section. Click Save button once more.
image

7. Clear the cache. DO NOT SKIP THIS STEP

**TO VIEW/CREATE A COLLECTION:**
To add collection, navigate to Content/Tripal Content/Add Tripal Content and select Germplasm Collection in the list.
To view collection, navigate to Content/Tripal Content and filter by Germplasm Collection 

image

NOTE: peculiarity seen when adding the field through Check for new fields link. It will set the field type to Chado Property and would set the formatter to Chado Property as a result, you could create a collection but unable to view it.

### CODE REVIEW

**Review by carolyncaron — COMMENTED** [review]
Hi Reynold,

I followed all of the steps on 2 separate clones (in the office and at home) and I'm having difficulties adding individual germplasm on both. The blue loading wheel continues spinning and never provides a dropdown list to choose from. I've tried typing the germplasm out fully and using the "Add to Collection" button but also, nothing happens (I suspect though, like many fields on KnowPulse, this will never work since it is expected that a germplasm will be selected from the dropdown of suggestions, but thought I'd try anyway). Screen Shot 2022-11-21 at 11 42 18 AM

I can confirm that uploading from a file worked on my computer at home. I will revisit trying this on my office computer.

For a minor suggestion, I recommend adding a description to the "Short Collection Identifier", similar to the description you provided in your screenshot. I think the mention that it is used in the URL is really helpful to the user!

**Comment by reynoldtan** [comment]
I was able to reproduce the error in a fresh KP clone and found that the issue was caused by using port number other than 80 for a Docker container. The fix above accounted this detail in http requests and should work on any port.

**Comment by carolyncaron** [comment]
Thanks Reynold, I confirmed that it works for me on both port 80 and a different one now! 👍 

The only other thing I've noticed which we may want to discuss with @laceysanderson is the use of the stock ID # prior to the germplasm name once one has been selected from the autocomplete dropdown (see screenshot). I believe our users may be confused by this as they are used to seeing the KP:GERM# version instead. However, I'm not sure whether this makes the module less generic and/or more complicated for other site administrators. 
Screen Shot 2022-11-22 at 2 32 51 PM

**Comment by reynoldtan** [comment]
As we have decided to unify all instances of autocomplete field to match the autocomplete field in chado I tried to implement it in this field but realized that both fields (Scientific name and Germplasm field) work in sync so that only germplasm that is of an organism will be suggested.

image

The current chado autocomplete lacks this filter option and suggests germplasm based on name/uniquename only as it is entered. 
[
function chado_autocomplete_stock($string = '') {...}](https://github.com/tripal/tripal/blob/f733e9dc4d65c4764fce3db5f4bd2bfb2efdc3df/tripal_chado/api/modules/tripal_chado.stock.api.inc#L31)

As a workaround, I managed to replicate the behaviour, particularly the final value returned when a selection has been made, that is in this notation

**Germplasm Name [id:Germplasm Id Number]**

**Comment by ruobinLiu** [comment]
After multiple rigorous tests, I am overall very happy with this germplasm collection field! Great job Reynold! I have no trouble  adding individual germplasm to the collection or bulk uploading a group of germplasm from a file. 

There is only one minor issue I want to point out here:

The little arrow in front of the "Germplasm Collection" doesn't load for me as shown in the screenshot
Screen Shot 2022-11-24 at 1 29 58 PM

Otherwise, everything works well as expected.

**Comment by carolyncaron** [comment]
Thanks Reynold, the formatting for the id in the autocomplete looks and works great! :+1: 
I just want to point out that the "Short Collection Identifier" could still use a description 😅 I also see the same issue that Ruobin pointed out on my clone. But otherwise, the functionality is looking merge-ready to me!

**Comment by reynoldtan** [comment]
Thank you... I have eliminated the problematic symbol and replaced it with a stronger title instead.
image

As for the short description for Short Collection Identifier field, this can be added through the Field Manager interface by clicking the edit option for the field and providing the text in either Label or Help text.

image

**Pull request merged**
